try {
  console.log(a)
} catch {
  console.log('err')
}